### ISSUE TITLE
Navigating to worksheet screens crash app on Android

### ISSUE THREAD

**Issue by JinsuElhance** [calblueprint/1951coffee#85]
On Pixel3a:
Logged into account and navigated to resources.

Worksheets -> 

Clicking on any of the following:
Question Cards
Espresso Coloring
Espresso Machine Labeling
Espresso Names

crashes the app.

**Comment by kennethlien** [comment]
Address can overflow on Jobs screen.

**Comment by JinsuElhance** [comment]
this is now its own issue #95

**Comment by averyyip** [comment]
Sad android reacts

**Comment by averyyip** [comment]
Fixed
