### ISSUE TITLE
I was marked "Contacted" on newly posted job I hadn't pressed "Interested" on

### ISSUE THREAD

**Issue by rlhe811** [calblueprint/1951coffee#94]
My username also wasn't on the airtable, but the job was grayed out
![IMG_4430](https://user-images.githubusercontent.com/46945934/79673897-8c329900-81a3-11ea-8092-7e6d70fc682c.PNG)

**Comment by rlhe811** [comment]
<img width="1347" alt="Screen Shot 2020-04-18 at 6 40 00 PM" src="https://user-images.githubusercontent.com/46945934/79673948-0bc06800-81a4-11ea-81ba-af4d3090a568.png">

**Comment by averyyip** [comment]
Admins will not remove trainees from interested jobs. Closed :)
